server:
  port: 8761 # Eureka Server portu

spring:
  application:
    name: eureka-server1 # Uygulama ad

eureka:
  client:
    fetch-registry: false   # Kendisi registry?den veri cekmez
    register-with-eureka: false # Kendisi registry?ye kaydolmaz


